export const ErrorCode = {
	// --- General ---
	UNKNOWN: 'RITE_UNKNOWN',

	// --- Adapter ---
	ADAPTER_ERROR: 'RITE_ADAPTER_ERROR',
	ADAPTER_NOT_FOUND: 'RITE_ADAPTER_NOT_FOUND',
	ADAPTER_MOUNT_FAIL: 'RITE_ADAPTER_MOUNT_FAIL',
	ADAPTER_UNMOUNT_FAIL: 'RITE_ADAPTER_UNMOUNT_FAIL',

	// --- Vue ---
	VUE_MOUNT_FAIL: 'RITE_VUE_MOUNT_FAIL',
	VUE_UNMOUNT_FAIL: 'RITE_VUE_UNMOUNT_FAIL',

	// --- React ---
	REACT_MOUNT_FAIL: 'RITE_REACT_MOUNT_FAIL',
	REACT_UNMOUNT_FAIL: 'RITE_REACT_UNMOUNT_FAIL',

	// --- Task ---
	TASK_ERROR: 'RITE_TASK_ERROR',
	TASK_NO_REGISTERED: 'RITE_TASK_NO_REGISTERED',

	// --- CLI ---
	CLI_SOURCE_DIR_NOT_FOUND: 'RITE_CLI_SOURCE_DIR_NOT_FOUND',
	CLI_MANIFEST_LOAD_FAIL: 'RITE_CLI_MANIFEST_LOAD_FAIL',
	CLI_MANIFEST_NOT_FOUND: 'RITE_CLI_MANIFEST_NOT_FOUND',
	CLI_NO_ENABLED_INJECTIONS: 'RITE_CLI_NO_ENABLED_INJECTIONS',
	CLI_MODULE_LOAD_FAIL: 'RITE_CLI_MODULE_LOAD_FAIL',
	CLI_RESOLVE_FAIL: 'RITE_CLI_RESOLVE_FAIL',
	CLI_CONFIG_INVALID: 'RITE_CLI_CONFIG_INVALID'
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
