export const ErrorCode = {
	// --- General ---
	UNKNOWN: 'MAKOO_UNKNOWN',
	FEATURE_NOT_FOUND: 'MAKOO_FEATURE_NOT_FOUND',
	FEATURE_CLEANUP_FAILED: 'MAKOO_FEATURE_CLEANUP_FAILED',
	FEATURE_REMOVED: 'MAKOO_FEATURE_REMOVED',
	FEATURE_NAME_CONFLICT: 'MAKOO_FEATURE_NAME_CONFLICT',
	INVALID_DECLARATION: 'MAKOO_INVALID_DECLARATION',
	LISTENER_HANDLER_FAILED: 'MAKOO_LISTENER_HANDLER_FAILED',
	LISTENER_BIND_FAILED: 'MAKOO_LISTENER_BIND_FAILED',
	DOM_WAIT_TIMEOUT: 'MAKOO_DOM_WAIT_TIMEOUT',
	LISTENER_TARGET_DETACHED: 'MAKOO_LISTENER_TARGET_DETACHED',
	LISTENER_UNBIND_FAIL: 'MAKOO_LISTENER_UNBIND_FAIL',

	// --- Adapter ---
	ADAPTER_NOT_FOUND: 'MAKOO_ADAPTER_NOT_FOUND',
	ADAPTER_NAME_CONFLICT: 'MAKOO_ADAPTER_NAME_CONFLICT',
	INJECTION_TARGET_DETACHED: 'MAKOO_INJECTION_TARGET_DETACHED',
	ADAPTER_MOUNT_FAIL: 'MAKOO_ADAPTER_MOUNT_FAIL',
	ADAPTER_UNMOUNT_FAIL: 'MAKOO_ADAPTER_UNMOUNT_FAIL',
	INJECTION_CONTAINER_REMOVE_FAIL: 'MAKOO_INJECTION_CONTAINER_REMOVE_FAIL'
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
