export const VueErrorCode = {
	VUE_HOOK_OUTSIDE_COMPONENT: 'MAKOO_VUE_HOOK_OUTSIDE_COMPONENT',
	VUE_HOOK_OUTSIDE_SCOPE: 'MAKOO_VUE_HOOK_OUTSIDE_SCOPE',
	VUE_PARTIAL_MOUNT_UNCONFIRMED: 'MAKOO_VUE_PARTIAL_MOUNT_UNCONFIRMED'
} as const;
